# Generated by Django 4.1.5 on 2023-02-06 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Force',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('basic_force_rating', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.PositiveSmallIntegerField()),
                ('int_bonus', models.SmallIntegerField()),
                ('wis_bonus', models.SmallIntegerField()),
                ('cha_bonus', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Troop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('level', models.PositiveSmallIntegerField()),
                ('number', models.PositiveSmallIntegerField()),
                ('ac', models.PositiveSmallIntegerField()),
                ('abilities', models.CharField(max_length=255)),
                ('spells', models.BooleanField()),
                ('force', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warmachine_core.force')),
            ],
        ),
        migrations.AddField(
            model_name='force',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='warmachine_core.leader'),
        ),
    ]
